### ISSUE TITLE
可以将命名替换成英文吗？

### ISSUE THREAD

**Issue by pengcheng789** [magiclen/JavaChineseCalendar#3]
使用中文进行函数和变量的命名有点难以接受且在使用的时候需要频繁进行输入法的切换，所以，可以麻烦您将中文命名替换成英文命名吗？

**Comment by magiclen** [comment]
您可以自行Fork自己的版本

**Comment by pengcheng789** [comment]
抱歉现在才看到您的信息，我会考虑您的建议，谢谢！
